pipeline {
    agent any

    stages {
        stage('Build') {
            dir("app/client") {
                steps {
                    cd 'app/client'
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....HIHI.dddd.asdasdasda'
            }
        }
    }
}
