pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir("/app/client") {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....HIHI.dddd.asdasdasda'
            }
        }
    }
}
