pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'npm init'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....HIHI'
            }
        }
    }
}
