pipeline {
    agent any

    stages {
        stage('Build-Client') {
            steps {
                dir("client") {
                    sh 'npm install'
                }
            }
        }
        stage('Build-Server') {
            steps {
                dir("server") {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. hallo icib bin ein test adsasdsdaadsasdasdasdasdasdaasdasdasda'
                //sh 'npm test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....HIHI.dddd.asdadasdaa'
            }
        }
    }
    post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'  
         }  
        //  failure {  
        //      mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'jenkinsbot@web.de', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "jenkinsbot@web.de";  
        //  }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }  
}
